### ISSUE TITLE
댓글 창이 새로고침 되지 않는 문제

### ISSUE THREAD

**Issue by samslow** [zzsza/zzsza.github.io#1]
Disqus 댓글이 게시글 이동시에 새로고침되지 않는 것 같습니다.

해당 게시글 페이지에서 새로고침하면 다시 잘 뜨긴 하지만 매번 새로고침하기는 역시 번거롭습니다.

저는 Disqus_thread 나 Disqus_Identifier 의 문제라 생각하여 검색 해 봤지만 아직 답을 못 찾았습니다.

**Comment by zzsza** [comment]
안녕하세요!
저도 인지하고 있는 문제인데, 음.. 계속 찾고 있어요! 찾게되면 말씀드릴게요!

요새 프론트 공부하면서 구조가 살짝... 보이고 있는데 조금만 기다려주세용 ㅇㅅㅇ/

**Comment by zzsza** [comment]
확인해본 결과, Adblock 때문에 새로고침이 안되고 있습니다- 
아래 링크 참고해보세요!
(아래 링크를 사용하면 DOM을 조작하지 못하는 케이스가 생겨서 저는 그냥 adblock을 해제하고 사용하려고 합니다)
https://github.com/zzsza/zzsza.github.io/pull/3

**Comment by samslow** [comment]
감사합니다 adblock 문제는 생각도 못 했네요 !
